import numpy as np
import math
import os
import shutil
from PIL import Image

import general as ut

if __name__ == '__main__':
	# for faster rcnn================
	# delete the flie whose size is smaller than 160Kb(ZH* 80) 
	#warning!!! these files are generated by origin size (use the api of slideExport NOT use the slideExportNew)
	#if use the slideExportNew.exe please change the threshold to 
	_dir = '/home/zhouming/data/cc/test_15cases_1024/SHHBSHSB181108127'
	out_dir = '/home/zhouming/data/cc/test_15cases_1024_fliter/'
	file_itr = ut.get_file_list(img_dir=_dir, img_suffix='.jpg')
	
	for file_name in file_itr:
		case_name = file_name.split('_')[0][:-8]
		#case_name = file_name.split('_')[0][:-10]
		if not os.path.exists(os.path.join(out_dir, case_name)):
			os.makedirs(os.path.join(out_dir, case_name))
		if (os.path.getsize(os.path.join(_dir, file_name+'.jpg'))>160*1000):
			shutil.copy(os.path.join(_dir, file_name+'.jpg'), os.path.join(out_dir, case_name))
		#shutil.copy(os.path.join(_dir, file_name+'.xml'), os.path.join(out_dir, case_name))
		print(file_name)
		print(case_name)